### ISSUE TITLE
Supporting multiple entry points

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#113]
In our own build we build all of the various entry points separately.

It should be possible to have all the entry points be a single "build operation".

The thing about this is that it does involve an API change - no longer just returning `{ code, map }` but returning a `{ code, map }` pair for each entry point built.

We could possibly even just have the build output a single `files: { [name]: source }` object where `files[filename]` contains the entry points, and do this as a breaking API change.

Alternatively the single-file v multiple entry point builds could be seen as separate APIs.

When done, the benefit of this would be that instead of duplicating code between the entry point builds, webpack can ensure they have code sharing between them.

This should reduce the self-hosting footprint size considerably too.

**Comment by rauchg** [comment]
Not sure I agree with this one (at least yet).

If you want multiple entrypoints, wouldn't you invoke `ncc build` multiple times? Perhaps using `-e` if you need to exclude something?

**Comment by guybedford** [comment]
> If you want multiple entrypoints, wouldn't you invoke ncc build multiple times? Perhaps using -e if you need to exclude something?

The benefit of permitting multiple entry points is you can get chunks that share code between them. So for example, it might be possible for acorn to be shared between Webpack and the asset reloader plugin for example (if they're the same version). This in turn reduces the build size and lazy load times.

**Comment by rauchg** [comment]
True but there's still the tradeoff in hitting disk in that case, as well as increasing complexity in the API. Open to thinking about this one, but probably not a priority.

**Comment by guybedford** [comment]
It turns out this is a prerequisite to the next.js integration due to the use of webpack internals effectively requireing a multiple entrypoints build.

**Comment by guybedford** [comment]
Since we're doing a major here I think this is a good opportunity to make output just a files map for ncc, as that will naturally support the multi-entry case a lot more nicely.

Hoping to get a PR up for this soon.

**Comment by LecrisUT** [comment]
@guybedford @styfle, was this never re-implemented?
