### ISSUE TITLE
Issue when using path.normalize

### ISSUE THREAD

**Issue by ajainarayanan** [zeit/ncc#119]
**Problem:**
I am trying to bundle up my express server to single file via ncc and running into issues. I need to package my node server along with browser code so checking ncc if this could reduce the package size I generate.

**Error:**
This is the error I am seeing
```
$ ncc build server.js 
Emitting directory /Users/ajainarayanan/Projects/nccdemo/assets as assets
(node:36438) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/ajainarayanan/Projects/nccdemo/dist/assets/asset1.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at module.exports.ncc.then (/Users/ajainarayanan/.config/yarn/global/node_modules/@zeit/ncc/dist/ncc/cli.js:2410:14)
    at <anonymous>
(node:36438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Sample repo to reproduce this issue: https://github.com/ajainarayanan/nccdemo

Please feel free to close if this is not the intended usage of ncc. Trying to explore solution that would fit my packaging.

**Comment by guybedford** [comment]
This bug is fixed in the unreleased commit on master at https://github.com/zeit/ncc/commit/e9c220ae6edd320b01fa90f04b82c82f71953e6e. The release should land soon, otherwise feel free to try the build from master here.

**Comment by ajainarayanan** [comment]
Thanks @guybedford! will look forward for the release.

**Comment by guybedford** [comment]
Closing, but let me know if you still have an issue with the coming release.

**Comment by ajainarayanan** [comment]
Sorry for resurrecting this again. @guybedford After upgrade to Node 10.16.2 the static folders for browser code are not longer copied to the output directory. I don't see any errors but only the files are copied to output directory and not other static directories. Is there some config that changed from 0.5.5 to 0.20.4?

**Comment by ajainarayanan** [comment]
Could this be related to the `webpack-asset-relocator-loader` loader? I see [the usage](https://github.com/zeit/webpack-asset-relocator-loader#usage-1) mentions about emitting entire directory which I believe is set to false by default.
