### ISSUE TITLE
0.1.18 -> 0.4.1 is a major change

### ISSUE THREAD

**Issue by leo** [zeit/ncc#127]
This error kept showing for `npm install -g now@canary` for Now CLI:

![image](https://user-images.githubusercontent.com/6170607/49616431-12847b80-f9b1-11e8-8aa5-13d491816f79.png)

This is because the download script is run through `ncc`.

[Downgrading](https://github.com/zeit/now-cli/pull/1725) fixed it. In turn, it seems like one of the releases in between should've been a major one.

**Comment by rauchg** [comment]
I think it's more of a bug, not a breaking change. @leo can you point us to:
- the source file on GitHub
- the `ncc build` instruction on GitHub
- ideally, the generated output

**Comment by leo** [comment]
You can test this by running `npm install -g now@13.0.0-canary.18`.

**Comment by leo** [comment]
More details:

- [Entrypoint](https://github.com/zeit/now-cli/blob/canary/download/install.js)
- [Build instruction](https://github.com/zeit/now-cli/blob/canary/package.json#L22)
- [Build output](https://unpkg.com/now@13.0.0-canary.18/download/dist/index.js)

**Comment by leo** [comment]
Resolved!
