### ISSUE TITLE
Add flow type support

### ISSUE THREAD

**Issue by gabrielperales** [zeit/ncc#129]
TypeScript is winning popularity, but I we are a lot of people who still using flow.

**Comment by rauchg** [comment]
I think one way that we could accomplish this is with optional `.babelrc` support, provided that adding the optional babel support doesn't increase our bundle too much or make us slower to boot.

If you are interested in working on that @gabrielperales, please let me know.

**Comment by zuohuadong** [comment]
now， facebook use typescript ~~
