### ISSUE TITLE
Node externals

### ISSUE THREAD

**Issue by gustavopch** [zeit/ncc#131]
Wouldn't it be a good idea to provide an option to use `webpack-node-externals` for those who want to let external packages out of the bundle?

**Comment by gustavopch** [comment]
Sure. As I understand, ncc currently bundles everything together including the dependencies, just like it's usual in the front-end.

But, for the backend, you don't necessarily want to bundle the dependencies. Some dependencies make webpack go crazy with warnings that would make sense in the frontend, but in the backend those warnings serve only the purpose of adding noise and distraction to the terminal. In that case, we can use `webpack-node-externals` in order to tell webpack we want to keep the dependencies out of the bundle (they will be installed with plain `npm install`).

Does that make sense?

**Comment by heysailor** [comment]
... if I understand correctly, it would also be good for the use case where there are many _potential_ dependencies which are not actually used.

I'm finding this with the `email_templates` npm library. It uses the `consolidate` template library - which has as its dependencies every template library under the sun. However, you only install the one you intend to use.

In this case, ncc produces a large list of unresolved dependencies which are not required in the built code.

**Comment by j** [comment]
I'd also prefer to not have ncc grab everything under the sun and just trust that I'm installing my node dependencies in an optimized fashion.  I'd like to also opt out of packing any externals.

**Comment by jvbianchi** [comment]
Another use case would be to avoid packing externals like `aws-sdk`

**Comment by gustavopch** [comment]
> Another use case would be to avoid packing some chosen externals, like `aws-sdk`

The current `externals` option seems to be enough for your use-case: https://github.com/zeit/ncc#programmatically-from-nodejs

**Comment by guybedford** [comment]
I believe the `externals` option exactly does cater to this use case. If there is anything that is missing in that we can discuss further and reopen if necessary.
