### ISSUE TITLE
TypeScript not found bug

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#133]
Despite TypeScript being bundled in, if not installed as a dependency, this is still thrown in https://github.com/TypeStrong/ts-loader/blob/master/src/compilerSetup.ts.

The reason is that it is running a `require(typeScriptCompilerName)` so this is similar to the resolution / require separation discussed in #41. Interestingly Browserify would actually handle this sort of thing fine as it includes a dynamic context, while the issue here is again the numeric ids in webpack.

There may be a way to ensure that the `typeScriptCompilerName` passed in to the require is the right thing, or to define a contextual manifest somehow that can make it do the right thing in the webpack side.

**Comment by rauchg** [comment]
Fixed
