### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by bogas04** [zeit/ncc#134]
Hi,

First of all, thanks for this awesome solution!

I was trying `ncc` on a [sails](https://sailsjs.com) project, and encountered this error.

```bash
$ ncc version
0.5.1

$ ncc build app.js -o server
/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/cli.js:2467
  throw e;
  ^

Error: EMFILE: too many open files, open '/Users/.../node_modules/machinepack-process/node_modules/lodash/function/memoize.js'
```

**Comment by sokra** [comment]
Could be. What's in ncc/cli.js:2467?

**Comment by guybedford** [comment]
All uses of `fs` should now be using graceful-fs so there should no longer be any EMFILE errors. If you are still seeing this though let us know as it should be an easy fix.
