### ISSUE TITLE
[proposal] Support umd format

### ISSUE THREAD

**Issue by amio** [zeit/ncc#144]
It would be easy to implement, and useful for some use cases. Would you consider supporting umd format?

**Comment by amio** [comment]
I wish to use `ncc` as a replacement for `browserify`/`microbundle`, it provide smaller bundle, built-in minifier, within a smaller footprint. Just right in the sweet spot. `microbundle` takes 100MB to install, `browserify` doesn't have a smooth minifier.

**Comment by rauchg** [comment]
Right now targeting browsers is a bit out of scope, but it's something we'll definitely consider in the future. Maybe Parcel 2.0 will fill in that niche elegantly.

Thanks for your issue @amio 🙏
