### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by gustavopch** [zeit/ncc#146]
I'm building a project that uses `firebase-admin` and I get a file named `grpc_node.node` in the build weighing 9.77MB. The `index.js` is also big with 4.45MB.

My question is: ncc is the preferred way to bundle stuff for Zeit's Now, right? Are these bundle sizes too big for Now? If they are, how would I be able to analyze the bundle size and to something to reduce it?

**Comment by rauchg** [comment]
It's definitely not "too big for Now", but it really makes me curious about what's going on inside `firebase-admin` 😅. You should bring this up with them, as `ncc` is just doing the correct thing.

Also, we've also noticed almost every single `@google/` and `@firebase/` project uses the native `grpc.node`, which gets re-built every time you `yarn` and creates some distribution challenges.

cc @mylesborins @davideast
