### ISSUE TITLE
Environment variables on `run`

### ISSUE THREAD

**Issue by gustavopch** [zeit/ncc#147]
As the title says, would it be a good idea for `run` to load environment variables from `.env` file?

**Comment by TooTallNate** [comment]
You should probably use the [`dotenv`](https://www.npmjs.com/package/dotenv) npm package for this. That way, it would work with both `node` and `ncc run`.

**Comment by gustavopch** [comment]
You are right. I thought it didn't work because my code was giving me an error, but on further investigation the error was completely unrelated. `dotenv` works just fine with `ncc run`.
