### ISSUE TITLE
Cannot find module 'socket.io-client/dist/socket.io.js'

### ISSUE THREAD

**Issue by gustavopch** [zeit/ncc#148]
I'm getting the error `Cannot find module 'socket.io-client/dist/socket.io.js'` on `ncc run`. Apparently, Socket.IO requires that file with `require.resolve(file)` and it's left out of the bundle by ncc. Is there a workaround for this?

**Comment by rauchg** [comment]
Seems like a bug in `ncc`, as it should be able to statically infer the requirement here and bundle that file.

**Comment by gustavopch** [comment]
Here's the stacktrace if it helps:
![image](https://user-images.githubusercontent.com/10941958/49843097-1f381380-fda5-11e8-927b-443606e332ec.png)

**Comment by styfle** [comment]
Fixed in #378
