### ISSUE TITLE
Support for tsconfig `paths`

### ISSUE THREAD

**Issue by odensc** [zeit/ncc#150]
In my `tsconfig.json` I use the `paths` option:

```json
"compilerOptions": {
  [...]

  "paths": {
    "@*": ["./src/*"]
  },
}
```

Which allows me to import files as such:

```ts
import validateToken from "@auth/jwt"; // => <root>/src/auth/jwt.ts
```

However ncc's module resolution is incompatible with this feature, giving the following error:

```bash
ncc: Module directory "<dir>" attempted to require "@auth/jwt" but could not be resolved, assuming external.
``` 

Something like `tsconfig-paths-webpack-plugin` could be used to support this configuration.

*I could submit a PR for this if there are no objections.*

**Comment by rauchg** [comment]
@odensc sounds like a good idea. I think `ncc` should support all the options of `tsconfig.json` predictably

**Comment by seawatts** [comment]
I am still getting the same error as @odensc 

tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "esnext",
    "lib": ["esnext"],
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": "./",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "esModuleInterop": true,
    "noUnusedLocals": false,
    "skipLibCheck": true,
    "noUnusedParameters": false,
    "declaration": true,
    "paths": {
      "@shuffl/*": ["src/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}

```

now.json
```json
{
  "version": 2,
  "env": {
    "IS_NOW": "true"
  },
  "builds": [
    {
      "src": "./src/**/*.ts",
      "use": "@now/node@canary"
    }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "/src/index" }
  ]
}
```

**Comment by odensc** [comment]
Hi @seawatts, if you could create a minimal repo that reproduces your issue that would be great. I can't seem to reproduce this with your basic tsconfig: https://gist.github.com/odensc/d52147afecfa697852171402cf5eb605

Perhaps it has something to do with `now`?

**Comment by liamdanielduffy** [comment]
Hi @odensc,

The reproduction for this issue is here:
https://github.com/liamdanielduffy/explorer-v2

I have a repo with roughly the following structure

```
+ api
--- + src
--- tsconfig.json
```

and the following lines in my tsconfig.json:

```
"paths": {
        "~/*": [
            "./api/src/*"
        ]
    }
```

Then I would like my import paths beginning with `~/`for all my \*.ts files in `src/` to be resolved from `src/`.

With this setup, I'm able to successfully run `now dev` to serve my API locally.

However, when I deploy to now, I see the following output error when I send a GET request to any of my endpoints:

```
Cannot find module '~'
Did you forget to add it to "dependencies" in `package.json`?
```

**Comment by odensc** [comment]
Hey @liamdanielduffy,

Again, I cannot reproduce this with your example and `ncc`. The output JavaScript runs fine and the imports are translated properly. So I believe it's an issue with Now, considering @seawatts was also using Now.

Sorry I couldn't help.

**Comment by liamdanielduffy** [comment]
No worries, I’ll follow up in the now-builders repo!
