### ISSUE TITLE
Output filename?

### ISSUE THREAD

**Issue by vitalyster** [zeit/ncc#152]
I want to name resulting js but there no option for that and output is always index.js

**Comment by rauchg** [comment]
You can use directories for this. e.g.: `-o my-dir`

**Comment by vitalyster** [comment]
And output will be `my-dir/index.js`, but not `my-dir/my-app.js`

**Comment by creazy231** [comment]
why is this closed without answering op's question?
@vitalyster you found any solution for this?

**Comment by styfle** [comment]
The directory can be used to run the application because the resulting file is `inde.js`.

For example, in your case:

```sh
ncc build -o my-app myfile.js
node my-app
```

**Comment by creazy231** [comment]
ok nvm 🙈 didn't know that you can run `node my-app` and it detects the index.js on its own. Nice to know :)

**Comment by GeekEast** [comment]
but what if I want to run myapp.js in aws lambda function?

Still didn't find any option to specify the bundle file name.

**Comment by GeekEast** [comment]
simply change this hard-coded filename is not difficult
![image](https://user-images.githubusercontent.com/24806887/118771135-56d60e80-b8c1-11eb-9b34-1f343f272c99.png)

**Comment by ortonomy** [comment]
> You can use directories for this. e.g.: `-o my-dir`

what a wonderfully unhelpful answer...
