### ISSUE TITLE
`ncc run` with -e flag not working

### ISSUE THREAD

**Issue by fmiras** [zeit/ncc#154]
-e flag is currently working only in `ncc build` and not in `ncc run`

How to test:
```js
// index.js
const puppeteer = require('puppeteer')
console.log('it works')
```
```bash
ncc run index.js -e puppeteer # -> "Error: Cannot find module 'puppeteer'"
ncc build index.js -e puppeteer -o dist && node dist # "it works"
```

**Comment by rauchg** [comment]
😨

**Comment by guybedford** [comment]
The reason for this would be the lack of a `node_modules` in the temporary directory that the app is run against.

We could symlink the `node_modules` there to the local one.

More consistent might be to symlink just `node_modules/[external]` for each known external to ensure nothing is brought through that shouldn't be.

**Comment by guybedford** [comment]
Fixed in https://github.com/zeit/ncc/pull/218.
