### ISSUE TITLE
Conditional requires break modules (webpack)

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#16]
Affecting:
- `pg`
- `redis`

**Comment by timneutkens** [comment]
Redis breaks here:
https://github.com/NodeRedis/node-redis-parser/blob/v.2.6.0/lib/parser.js#L341-L350

Hiredis and the conditional require were removed in 3.0.0, but `redis` doesn't use that:
https://github.com/NodeRedis/node-redis-parser/releases/tag/v.3.0.0

I guess we could replace the require with a synthetic `throw new Error('require failed')` (but in the official node.js way with error code etc), that way if the branch is hit it'll error out just like the source code would
