### ISSUE TITLE
Too high memory usage.

### ISSUE THREAD

**Issue by axetroy** [zeit/ncc#165]
I pack a project here https://github.com/axetroy/webuild

It take about 2.2G memory usage.

And you kown, `V8` only allow you use `1.5G` in 64bit machine

And I have to run like this:

```bash
node --max-old-space-size=4096 /Users/axetroy/.nvm/versions/node/v10.14.2/bin/ncc build bin/webuild
```

**Comment by guybedford** [comment]
There's not really much we can do apart from the above to reduce memory usage, as we're bound by Webpack's own memory handling here unfortunately.

How big is your output build out of interest?

**Comment by guybedford** [comment]
Closing as this is more of a state of JavaScript tools ( / webpack ) than a bug.

**Comment by axetroy** [comment]
@guybedford 
At present, webpack does not solve this problem.

Should we wait for webpack to solve the problem before close this issue?
