### ISSUE TITLE
FS inlining support

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#17]
Lack of fs inlining breaks modules like:
- `saslprep`
- `pdfjs` (`fontkit` dep)

It yields a warning in `mongoose`, but that's due to `find-package-json`, which *I think* might not be statically analyzable[1]

[1] famous last words

**Comment by timneutkens** [comment]
Sounds like this might work:
https://github.com/webpack-contrib/transform-loader
Combined with:
https://github.com/browserify/brfs

**Comment by rauchg** [comment]
Let's make sure it works for this case:
https://github.com/zeit/ncc/issues/11

**Comment by rauchg** [comment]
Fixed by #39
