### ISSUE TITLE
Watch in run mode

### ISSUE THREAD

**Issue by pontusab** [zeit/ncc#191]
I'm now building my API using `ncc` instead of custom webpack config and it's really nice to skip all the extra boilerplate that I have. But I would like to use it in dev mode too, I'm running `ncc run api/index.ts` but I'm struggling to have a complete experience with watching the changes. 

Is there any support for something like `ncc run -w api/index.ts` or another way to handle this? 

Thanks!

**Comment by rauchg** [comment]
For now we're cautious about introducing watching, because we want to see how fast we can get without it. In other words, watch mode aggressively optimizes for warm situations, and that has made authors a bit 'relaxed' about cold boots, which are also very important.

**Comment by pontusab** [comment]
Understand. I was thinking of using ncc even under development so it would be handy. Is the recommended way to only use ncc to build?

**Comment by maxbeatty** [comment]
@pontusab I'm using [nodemon](https://nodemon.io) for watching during development and happy with it fwiw (`__dev__.ts` is a simple http server)

```
nodemon --exec 'ncc run' __dev__.ts
```
