### ISSUE TITLE
Unknown or unexpected option: -w

### ISSUE THREAD

**Issue by brunolemos** [zeit/ncc#193]
`ncc build src/index.ts -e electron -w`

`ncc version: 0.7.0` _although ncc version shows 0.6.0_

**Comment by rauchg** [comment]
Version issue has been fixed in `0.8.1`. We don't intend to support watching until we ship v8 snapshots and we make webpack full cache scenarios faster. In other words, re-running `ncc build` should be much faster than it is now

**Comment by brunolemos** [comment]
The readme currently mentions the -w flag, maybe it'd be better to remove it for now then
