### ISSUE TITLE
module 'oracledb' does not get included

### ISSUE THREAD

**Issue by gretel** [zeit/ncc#205]
in a project three modules having extensions (`segfault-handler`, `sampling_heap_profiler`, `oracledb`) are declared in `package.json`, resolved and built fine using `yarn`.

for some reason this particular module does not get included in the collection.

therefore, on loading `index.js` it can not be found:

```
...
Cannot find module /opt/dist/build/Release/oracledb.node
...
    at Object.module.exports.module.exports (/opt/dist/index.js:367750:15)
    at __webpack_require__ (/opt/dist/index.js:22:30)
    at Object.<anonymous> (/opt/dist/index.js:108275:18)
    at __webpack_require__ (/opt/dist/index.js:22:30)
    at Object.<anonymous> (/opt/dist/index.js:180152:17)
    at __webpack_require__ (/opt/dist/index.js:22:30)
    at Object.module.exports.Object.defineProperty.value (/opt/dist/index.js:484672:27)
    at __webpack_require__ (/opt/dist/index.js:22:30)
    at Object.module.exports.module.exports (/opt/dist/index.js:159034:22)
    at __webpack_require__ (/opt/dist/index.js:22:30)
```

strangely, copying the module to this exact location does not make any difference.

checking on overall integrity, file content and permission did not hint on anything.

**Comment by guybedford** [comment]
Ok the issue here is detection of the following require case:

```js
var path = "./path/to/binary.node";
require(path);
```

applying in general, not just for the binary loading use case.

We should be able to get webpack to see this by basically doing something like the following transform:

```js
var path = "./path/to/binary.node";
require("./path/to/binary.node");
```

that is, inlining the path string.

**Comment by gretel** [comment]
> that is, inlining the path string.

thank you!

**Comment by guybedford** [comment]
@sokra do you think it would be possible to add support for something like this in Webpack, or should we do our own analysis here too? See https://github.com/zeit/ncc/issues/205#issuecomment-452692597 for the approach.

**Comment by guybedford** [comment]
On further analysis here, we actually do exactly support the pattern described in https://github.com/zeit/ncc/issues/205#issuecomment-452692597 just fine.

Rather the issue comes from this code:

```js
var oracledbCLib;
var oracledbInst;
var Lob = __webpack_require__(591).Lob;
var pool = __webpack_require__(695);
var connection = __webpack_require__(929);
var nodbUtil = __webpack_require__(847);
var createPoolPromisified;
var getConnectionPromisified;
var poolCache = {};
var tempUsedPoolAliases = {};
var defaultPoolAlias = 'default';

//  Load the Oracledb binary

var binaryLocations = [
  '../' + nodbUtil.RELEASE_DIR + '/' + nodbUtil.BINARY_FILE,  // pre-built binary
  '../' + nodbUtil.RELEASE_DIR + '/' + 'oracledb.node',       // binary built from source
  '../build/Debug/oracledb.node'                              // debug binary
];

for (var i = 0; i < binaryLocations.length; i++) {
  try {
    oracledbCLib = require(binaryLocations[i]);
    break;
  } catch(err) {
    if (err.code !== 'MODULE_NOT_FOUND' || i == binaryLocations.length - 1) {
      var nodeInfo;
      if (err.code === 'MODULE_NOT_FOUND') {
        // none of the three binaries could be found
        nodeInfo = `\n  Looked for ${binaryLocations.map(x => __webpack_require__(589).resolve(__dirname + '/lib', x)).join(', ')}\n  ${nodbUtil.getInstallURL()}\n`;
      } else {
        nodeInfo = `\n  Node.js require('oracledb') error was:\n  ${err.message}\n  ${nodbUtil.getInstallHelp()}\n`;
      }
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
    }
  }
}
```

so this is probably best handled as a special case unfortunately.

**Comment by gretel** [comment]
cool thanks 👍

**Comment by code-ape** [comment]
This appears to be broken as of OracleDB 5.x. I can open a PR to support this if desired?

**Comment by guybedford** [comment]
@code-ape if you're able to diagnose the issue or work on a PR that would be very welcome.

**Comment by Nodirbek3d** [comment]
How did you guys resolve this issue? My project uses oracle db and I am getting this error:
`ERROR	Error: NJS-045: cannot load a node-oracledb binary for Node.js 14.15.4 (linux x64) 
  Looked for /var/task/node_modules/oracledb/build/Release/oracledb-5.1.0-linux-x64.node, /var/task/node_modules/oracledb/build/Release/oracledb.node, /var/task/node_modules/oracledb/build/Debug/oracledb.node, /var/task/node_modules/oracledb/lib/node_modules/oracledb/build/Release/oracledb-5.1.0-linux-x64.node, /var/task/node_modules/oracledb/lib/node_modules/oracledb/build/Release/oracledb.node
  Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
    at Object.<anonymous> (/var/task/node_modules/oracledb/lib/oracledb.js:87:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/task/node_modules/oracledb/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
RequestId: 85023a2f-d7bc-4286-8517-322719010ab6 Error: Runtime exited with error: exit status 1
Runtime.ExitError`
