### ISSUE TITLE
Require is unable to resolve JSON files without explicit ".json" extension

### ISSUE THREAD

**Issue by nik-garmash** [zeit/ncc#22]
For example, I'm trying to build an app with FIrebase Admin SDK, and it fails.

`npx ncc index.js -o bundle.js`
```
Module directory "/node_modules/@google-cloud/firestore/build/src/v1beta1" attempted to require "./firestore_client_config" but could not be resolved, assuming external.
```

`/node_modules/@google-cloud/firestore/build/src/v1beta1` folder looks like this:
<img width="229" alt="screenshot 2018-11-19 at 11 44 59" src="https://user-images.githubusercontent.com/793851/48702196-99370b80-ebf0-11e8-8201-e42bf24a0f13.png">

And the `require()` looks like this `const gapicConfig = require('./firestore_client_config');`

**Comment by rauchg** [comment]
This has been solved in `0.1.6`
