### ISSUE TITLE
require.main === module is different after ncc

### ISSUE THREAD

**Issue by ajcrites** [zeit/ncc#224]
This is [node.js's recommended method for determining the main module](https://nodejs.org/api/modules.html#modules_accessing_the_main_module).

If you have a file like:

```js
// index.js
console.log(require.main === module);
```

```sh
$ node .
true
$ ncc run .        # or build
false
```

`ncc` should have the output file function the same as when using `node`.

**Comment by futagoza** [comment]
Can't this be fixed by simply doing this:
```js
{
    plugins: [
        new webpack.DefinePlugin( {
            "require.main": "require.main",
        } ),
    ],
}
```
