### ISSUE TITLE
Error on second run because process wasn't cleaned up when killed.

### ISSUE THREAD

**Issue by wcastand** [zeit/ncc#227]
So the first run is working perfectly but if i kill the process and rerun it, i get this error : 

`Error: Application at dev-server.ts is already running or didn't cleanup after previous run.To manually clear the last run build, try running "rm -rf /var/folders/k1/f1hwwnjx793cq6jdbs31hv9r0000gn/T/d41d8cd98f00b204e9800998ecf8427e".
`

This is the command i'm using : `yarn ncc run dev-server.ts --watch`
I tried without the `--watch` option but it didn't change the result.

This is the dependencies : 
```json
"dependencies": {
  "apollo-server-micro": "^2.2.2",
  "bcryptjs": "^2.4.3",
  "graphql": "^14.0.2",
  "graphql-iso-date": "^3.6.1",
  "jsonwebtoken": "^8.4.0",
  "micro": "^9.3.3",
  "micro-cors": "^0.1.1",
  "mongoose": "^5.3.13",
  "mongoose-unique-validator": "^2.0.2"
},
"devDependencies": {
  "@zeit/ncc": "^0.9.0",
  "dotenv": "^6.2.0",
  "typescript": "^3.2.2"
},
```
and the tsconfig.json : 
```json
{
  "compilerOptions": {
    "target": "es2015",
    "moduleResolution": "node"
  }
}
```

**Comment by benseitz** [comment]
Just ran into the same error. Thank you for the pull request @wcastand!

**Comment by wcastand** [comment]
Hi, glad to help but the one you should thank for the Pr is @guybedford  :P
