### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by henderea** [zeit/ncc#238]
There seem to have been multiple releases since the last tag was created on this repo.  I have no idea what changes have been made, and I really like to know how things are changing with each release.  Can you either do a better job of keeping the tags and Releases up to date or add a `CHANGELOG.md` file?  There have been some releases on npm that haven't been tagged here in the past, but it seems like the tagging has completely stopped.  Is the `master` branch not the place to look for those things?

**Comment by rauchg** [comment]
@henderea my bad. We'll publish release notes soon, and we are working on doing so more automatically.

**Comment by rauchg** [comment]
In the mean time, the commit history should be quite clear

**Comment by rauchg** [comment]
Done!
