### ISSUE TITLE
Implement relocate-loader in Next.js

### ISSUE THREAD

**Issue by timneutkens** [zeit/ncc#240]
Next.js has similar issues as `ncc` with relation to readFile files that aren't available.

Eg https://github.com/zeit/next.js/issues/6073

We don't want to add ncc as dependency to Next.js because it would slow down the build process. However it'd make sense to add relocate-loader.

**Comment by timfish** [comment]
@guybedford many thanks for pulling the relocate loader out. It works great on its own! ♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️

**Comment by guybedford** [comment]
Glad to help, look forward to following the integration there!

**Comment by Timer** [comment]
Closing in favor of https://github.com/zeit/next.js/pull/6204. I guess we can consider this "done".
