### ISSUE TITLE
ncc using webpack breaks build

### ISSUE THREAD

**Issue by NathanielHill** [zeit/ncc#256]
Not really sure where to raise this issue, but I'm having trouble sharing modules in a yarn workspaces monorepo that need to be transpiled.

I've setup `@babel/register` to transpile an imported React component which work fine locally.

However, when `ncc` tries to bundle everything with webpack it fails to parse the JSX.

**Comment by rauchg** [comment]
`@babel/register` performs transpilation at runtime, correct? Are you sure you want to do that?

**Comment by NathanielHill** [comment]
No, I actually don't want to do that. I just ran into so many problems trying other techniques that I was giving this a shot.

**Comment by NathanielHill** [comment]
It would probably work, except `ncc` is trying to bundle into a single file using webpack. If I have a webpack or babel config, will it honor it?

**Comment by NathanielHill** [comment]
I'm going to try and solve my issues by using the `prepare` lifecycle script in `package.json` to do my own transpiling.

Closing for now
