### ISSUE TITLE
Path separator should be escaped on Windows

### ISSUE THREAD

**Issue by alpaix** [zeit/ncc#272]
`ncc` generates `require` path with platform specific path separators 
```js
module.exports = require("./build\Release\zmq.node")
```
If not correctly escaped, this statement causes a runtime error
> Error: Cannot find module './buildReleasezmq.node'

For repro [nteract/kernel-relay](https://github.com/nteract/kernel-relay)

**Comment by alpaix** [comment]
cc @rgbkrk

**Comment by guybedford** [comment]
This should be resolved now, please let me know if it comes up again at all.

**Comment by rgbkrk** [comment]
Thank you!
