### ISSUE TITLE
dynamic resolve fails

### ISSUE THREAD

**Issue by bfulop** [zeit/ncc#277]
Uglify JS (which is a dependency of another lib I'm using) [uses this import format](https://github.com/mishoo/UglifyJS2/blob/ea999b0e9261a9035af5c1f35ffe68bb83f29719/tools/node.js#L3)

```javascript
var FILES = [
    "../lib/addnumbers.js",
].map(function(file){
    return require.resolve(file);
});
```

This format fails with the `ncc run <filename>` command.

Possibly a duplicate of #41 

Here's a simple repo to demonstrate the issue : https://github.com/bfulop/zeitwithyarn

It fails with this error:

```
	var e = new Error("Cannot find module '" + req + "'");
         ^
Error: Cannot find module '../lib/addnumbers.js'
    at Function.webpackEmptyContext [as resolve] (/private/var/folders/r2/br0p741168qg5n2h65fzsdz40000gn/T/d41d8cd98f00b204e9800998ecf8427e/index.js:84:10)
    at /src/addtwo.js:6:1
    at Array.map (<anonymous>)
    at Object.457 (/src/addtwo.js:5:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.138 (/date.js:1:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at startup (/webpack:bootstrap:33:1)
    at /webpack:bootstrap:37:1
    at Object.<anonymous> (/private/var/folders/r2/br0p741168qg5n2h65fzsdz40000gn/T/d41d8cd98f00b204e9800998ecf8427e/index.js:43:10)
```

**Comment by bfulop** [comment]
It's just a temporary hack, but preprocessing my code with Rollup, makes it compatible with ncc tool.

Here's the minimal repo, check the `rollup.config.js` file: 
https://github.com/bfulop/zeitwithyarn

Please note, I don't really know why it works, and what I was doing exactly 🤷‍♂️

**Comment by homerjam** [comment]
Would/does specifying `externals` work?

**Comment by bfulop** [comment]
I haven't tried that. In this case, I would need to deploy to Zeit the output of the ncc build run?

My workaround was to pre-bundle the MJML package with NCC, publish it to npm, and import that in my app. This way I can just do `$ now` and it works.

https://www.npmjs.com/package/mjml-ncc-bundle

**Comment by homerjam** [comment]
Yes, thats how I understand it. Although I'm not sure it's possible, I think it may require a modification to the `now-node` builder to allow specify the ncc options.

Thanks for letting me know about the workaround - I'll do the same for now!

**Comment by homerjam** [comment]
I've tested using externals and can confirm this appears to work

```
ncc run index.js -e uglify-js
```

**Comment by guybedford** [comment]
Since this is such a common problem, we've included this as the default behaviour in https://github.com/zeit/ncc/pull/307.
