### ISSUE TITLE
Can't seem to bundle external `.js` assets

### ISSUE THREAD

**Issue by TooTallNate** [zeit/ncc#278]
I'm trying to bundle a `bootstrap.js` file that gets executed by a separate `node` process, and thus _should not_ be compiled into the webpack bundle, but _should_ be bundled as an external asset in the `dist` dir.

Let's try it out, with the file named `bootstrap.js`:

```
$ tree
.
├── bootstrap.js
└── t.js

0 directories, 2 files

$ cat t.js
const { statSync } = require('fs');
const p = `${__dirname}/bootstrap.js`;
console.log(p);
console.log(statSync(p));

$ ncc build t.js
1kB  dist/index.js   [671ms]

$ tree dist/
dist/
├── index.js
└── index.js.map

0 directories, 2 files
```

The `bootstrap.js` file is not in the `dist` dir! Ok now let's try again after renaming `bootstrap.js` to simply `bootstrap`:

```
$ tree
.
├── bootstrap
└── t.js

0 directories, 2 files

$ cat t.js
const { statSync } = require('fs');
const p = `${__dirname}/bootstrap`;
console.log(p);
console.log(statSync(p));

$ ncc build t.js
0kB  dist/bootstrap
1kB  dist/index.js    [759ms]

$ tree dist/
dist/
├── bootstrap
├── index.js
└── index.js.map

0 directories, 3 files
```

`bootstrap` is there!

I can work around this easily enough for now, but ultimately I think this use case should be supported.

**Comment by guybedford** [comment]
Are you sure you are running the latest version here?

In previous versions, we skipped .js file emission as it would typically not be an asset.

But as of a few releases ago this was changed to always emit ".js" files for this sort of use case.

It's definitely a bug otherwise.

**Comment by TooTallNate** [comment]
Seems it works with the latest ncc using my simple repro here. However, I'm still seeing it in now-cli where I discovered this issue. I'll DM you to try to drill it down further. Closing this one for now.

**Side idea:** ncc should print its own version during `ncc build` to eliminate this kind of uncertainty and make bug reports easier to understand.

**Comment by rauchg** [comment]
> **Side idea:** ncc should print its own version during `ncc build` to eliminate this kind of uncertainty and make bug reports easier to understand.

We really need to develop this habit with all our CLIs
