### ISSUE TITLE
Supporting `__dirname` wildcards

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#297]
Consider for example:

```js
fs.readFileSync(__dirname + './languages/' + lang  + '.js');
```

we can in this scenario know that this corresponds to an asset of the form `./languages/*.js` and emit assets based on this wildcard.

This would support eg `unfluff` as detailed in https://github.com/zeit/ncc/issues/216#issuecomment-467647324.

**Comment by styfle** [comment]
Fixed in #378
