### ISSUE TITLE
Problem to install a certain module

### ISSUE THREAD

**Issue by MAPESO** [zeit/ncc#300]
This error is related to `ncc` since the problem is presented in `now` and `now-dev`

## Main problem 😿 

when installing the `firebase-admin` module for some strange reason it causes the time in the compilation increases dramatically to the point of reaching this measurements of **17m 36s**. As a result, due to an excessive wait time `localhost` is never loaded.

**NOTE:** the gif does not represent the total compilation time

![2019-03-04 22 31 59](https://user-images.githubusercontent.com/16585386/53794296-50803580-3ef5-11e9-8ca5-e10de8e5a60a.gif)

<img width="730" alt="screen shot 2019-03-04 at 21 17 44" src="https://user-images.githubusercontent.com/16585386/53794103-e36ca000-3ef4-11e9-9b82-fab9c36ec58a.png">

### How to reproduce the problem ? 🐛 

1. clone this [repository](https://github.com/MAPESO/error-fire)
2. delete the `.git` folder to avoid compilation failures
3. `yarn install` or `npm install`
4. run the command `DEBUG = * fun * ~ /Downloads/now-macos dev --debug --port 8080`

###  Could it be a cache problem ? 🤔 

no, I have been cleaning the cache constantly to avoid this kind of problems, but unfortunately the result is the same, when you install dependency of `firebase-admin`, `ncc` remains frozen.

### package.json

![carbon 03 54 15](https://user-images.githubusercontent.com/16585386/53823880-416ea700-3f38-11e9-94ef-a1bfe3c01240.png)

**Comment by MAPESO** [comment]
zeit/now-builders#245

**Comment by MAPESO** [comment]
It seems that the ncc and user folders increase the compile time.

**Comment by guybedford** [comment]
@TooTallNate does your PR in now-builders mitigate this issue? Or is there something we need to look at on the ncc side here?

**Comment by kevingelion** [comment]
I'm able to deploy, however, any request to Firebase beyond authenticating is met with similar errors to: `Unhandled "error" event. (/var/task/google/api)`

**Comment by MAPESO** [comment]
I will close this issue. Unfortunately the problem is the same however the behavior is different 🙍
