### ISSUE TITLE
typescript - define tsconfig file

### ISSUE THREAD

**Issue by maku** [zeit/ncc#302]
I would like to define a specific tsconfig file when running ncc.
Is this this possible?

**Comment by guybedford** [comment]
Yes, ncc will use the local tsconfig.json file when running TypeScript.

**Comment by maku** [comment]
@guybedford - we have different tsconfig files in the project.
I want to specifiy which tsconfig ncc should use (e.g. server/tsconfig.app.json)

**Comment by zuohuadong** [comment]
+1 @maku

**Comment by zuohuadong** [comment]
@guybedford 
like: 
`tsc -p apps/nest-upms/tsconfig.json`
`tsc -p apps/nest-abc/tsconfig.json`
