### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#31]

**Comment by rauchg** [comment]
It would be neat to self-host this. I think [this bug](https://github.com/zeit/ncc/commit/f0fae030524e1e2ea7150cd3aea4989d09c1c6e7) wouldn't have happened if `ncc` was written in TypeScript.

**Comment by romainquellec** [comment]
> if ncc was written in TypeScript

Well, it's not too late for a "rewrite" in TS !

**Comment by rauchg** [comment]
Indeed. The idea is to port it once we can self-host TS. I was just commenting on why TS is so valuable :)
