### ISSUE TITLE
Change `amd` option to false

### ISSUE THREAD

**Issue by styfle** [zeit/ncc#315]
Since `ncc` is a node compiler and node can't use AMD, we can disable it.

There is a new option that will be released in the next version of webpack `amd: false`

https://github.com/webpack/webpack/pull/8890

**Comment by guybedford** [comment]
We already have this - https://github.com/zeit/ncc/blob/master/src/index.js#L170.

**Comment by styfle** [comment]
@guybedford I don't believe that is the same setting because this feature wasn't introduced until a couple weeks ago in [webpack@4.30.0](https://github.com/webpack/webpack/releases/tag/v4.30.0).

The line you linked to is for the parse option but this is a top-level webpack option.

**Comment by guybedford** [comment]
Ahh I see. Do we need a separate PR to bring it to the Webpack 5 branch (used by ncc) as well then?

**Comment by styfle** [comment]
@guybedford I searched the release notes for webpack 5 and don't see it announced so I think the answer is yes, we need a separate PR for webpack 5

**Comment by guybedford** [comment]
Created the port PR at https://github.com/webpack/webpack/pull/9074.

**Comment by styfle** [comment]
Fixed in 388
