### ISSUE TITLE
TS source maps look wrong when throwing Error

### ISSUE THREAD

**Issue by styfle** [zeit/ncc#316]
I got a report from @javivelasco that the source maps looked wrong for errors in Sentry.

Typically, the `.js` + `.js.map` can be used by Sentry to show the original line number that the error was thrown instead of the bundled/webpack line number. However, this was not working so I made a small example to reproduce what I believe is the root cause.

## Steps to reproduce

```sh
git clone https://github.com/styfle/ncc-bug-sourcemap
cd ncc-bug-sourcemap
yarn

yarn build         # builds with tsc proper
node dist/index.js # note the error output

rm -rf dist

ncc build index.ts --source-map
node dist/index.js # note the error output
```

The most notable difference is the that some of the lines in the stack trace say `.ts` instead of `.js` and don't include a full path.

## Diff

![image](https://user-images.githubusercontent.com/229881/54544983-142dea00-4977-11e9-87a0-9dbbce69a6fd.png)

**Comment by guybedford** [comment]
Did you try building with sourceMapRegister: false? We use a custom node
source maps solution by default.

**Comment by styfle** [comment]
@guybedford This looks good!

```sh
ncc build index.ts --source-map --no-source-map-register
node dist/index.js
```

## Diff

![image](https://user-images.githubusercontent.com/229881/54545830-d762f280-4978-11e9-8c0d-9e99732a40de.png)


@guybedford Why is source map register enabled by default?

**Comment by guybedford** [comment]
Because ncc stack traces are otherwise completely undecipherable when running in Node.js, and with this register addon we can always know the original file easily from the stack trace without any more work.

**Comment by styfle** [comment]
> Because ncc stack traces are otherwise completely undecipherable when running in Node.js

That makes sense for the use case when the user is no generating source maps (default behavior).

But when the user explicitly requests source maps, it seems strange.

For example, I can't think of a scenario where the user would want to use `ncc build index.ts --source-map` instead of `ncc build index.ts --source-map --no-source-map-register`.

Was this option added to maintain backwards compatibility or is there a use case I'm not thinking of 🤔

**Comment by guybedford** [comment]
By default, source maps are not generated in `ncc build`, so that `ncc build index.ts` will have no source maps in the output.

So `ncc build index.ts --source-map && node dist` gives you a version with debugging support which is what users might typically want for source maps in a Node.js environment.

The `--no-source-map-register` is then the opt-out of the Node.js source maps "polyfill".

I'm certainly open to changing things though.

**Comment by styfle** [comment]
Closing in favor of #319
