### ISSUE TITLE
ncc attempting to compile unrelated TypeScript files

### ISSUE THREAD

**Issue by Problematic** [zeit/ncc#321]
Repro here: https://github.com/Problematic/ncc-build-repro
now deployment logs here: https://zeit.co/problematic/ncc-build-repro/deployment/5uaokkbrh/logs

If I have two independent subdirectories, each with their own package.json files, and `ncc build` a file in one of them, ncc fails with TS errors unless npm dependencies have _also_ been installed in the second subdirectory, even if the ncc build target does not reference the other subdirectory at all. This becomes visible when deploying with `now`, since only the node_modules for the target subdirectory are installed during the build process, but can be reproduced locally as well.

**Comment by guybedford** [comment]
I believe this is the same issue discussed in https://github.com/zeit/ncc/issues/170#issuecomment-448038109. Basically nested tsconfigs are checked and validated, and will cause errors in the build even if they are not used. This is a limitation of the tsconfig-paths-webpack-plugin approach I believe.

**Comment by guybedford** [comment]
Let's track progress on this "feature" in https://github.com/zeit/ncc/issues/362.
