### ISSUE TITLE
Building Packages that Aren't Lambda Friendly

### ISSUE THREAD

**Issue by j** [zeit/ncc#328]
I'm trying to switch internal apps to monorepos and use ncc to build, but am coming across fails in node v8.10 (Lambda)

```
async function* asyncIterator() {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I believe it's because I'm using `type-graphql` which uses graphql subscriptions which rely on async generators, however, shouldn't ncc solve this?

**Comment by styfle** [comment]
I am unable to reproduce.

I created a file `index.js` with an generator like so:

```js
function* range(start = 0, end = Infinity, step = 1) {
    let count = 0;
    for (let i = start; i < end; i += step) {
        count++;
        yield i;
    }
    return count;
}


for (let val of range(1, 10)) {
	console.log(val);
}
```

Then `ncc run index.js` works just fine.

**Comment by j** [comment]
@styfle i think it’s when a 3rd party module that another package is requiring is using generators in their built code and I don’t think ncc is touching it.

**Comment by makamekm** [comment]
> I am unable to reproduce.
> 
> I created a file `index.js` with an generator like so:
> 
> ```js
> function* range(start = 0, end = Infinity, step = 1) {
>     let count = 0;
>     for (let i = start; i < end; i += step) {
>         count++;
>         yield i;
>     }
>     return count;
> }
> 
> 
> for (let val of range(1, 10)) {
> 	console.log(val);
> }
> ```
> 
> Then `ncc run index.js` works just fine.

You need to run it with node 8 in order to reproduce.

**Comment by styfle** [comment]
I don't believe this is an issue with `ncc`.

> You need to run it with node 8 in order to reproduce.

Node 8 doesn't support async generators https://node.green/#ES2018-features-Asynchronous-Iterators

Try running the output with Node 10.3 or newer.

**Comment by j** [comment]
Still a different error in that issue. But their solution seems like a hack.

**Comment by j** [comment]
@styfle that was the point.  I thought I'd be able to use ncc like webpack/babel to transform incompatible code to node 8 compatible (AWS Lambda... what now deploys to?)

**Comment by styfle** [comment]
> I thought I'd be able to use ncc like webpack/babel

These are two different projects with two different goals. `ncc` is similar to webpack (in fact it depends on webpack). However, a Babel-like down-compile/polyfill is not the [goal](https://github.com/zeit/ncc#motivation) of `ncc` and not supported. You can achieve that with TS by setting `target: es2015`.

**Comment by j** [comment]
Already targeting es2015.  I don't think typescript is touching 3rd party node_modules.  Just transforming my own source.

The issue seems to be with mongodb.

https://github.com/mongodb/node-mongodb-native/blob/e0826fb10a74976079c94e9af43c1a9798ce3094/lib/async/async_iterator.js

**Comment by rufoot** [comment]
@styfle Do you mean length function doesn't work in Lambda function?

I have coded as below. And I have got an error.

`var unread_msg = dtc_data.Items.map(data => {
                        if (data.acknowledged == false)
                            return data;
                    })
                    var counts = unread_msg.length;
                    return cb(null, testValue);`

It looks like Lambda doesn't support the length function for getting the length of an array. Is it right?

**Comment by styfle** [comment]
@rufoot You must be having a different problem.

[Array.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length) has been available in every version for EcmaScript/JavaScript.

**Comment by rufoot** [comment]
I think so. But I have got an error with `unread_msg.length`. As you can see `unread_msg` should be an array value. And length function is not working exactly. I need to fix it asap.

**Comment by styfle** [comment]
@rufoot Can you create a new issue with the steps to reproduce?
