### ISSUE TITLE
Weird behaviour around google-proto-files

### ISSUE THREAD

**Issue by igorklopov** [zeit/ncc#330]
```
mkdir -p google-gax/build/src
echo "var googleProtoFilesDir = require('google-proto-files')('..');" > google-gax/build/src/grpc.js
echo "require('./google-gax/build/src/grpc.js');" > index.ts
echo "{}" > tsconfig.json
ncc build index.ts
```

This script causes ncc throw unhandled rejection `Cannot split a chunk that has already been edited`. Tested against 99e71ef.

**Comment by styfle** [comment]
@igorklopov I confirmed this is a bug during the build step.

The workaround is to change your one line into two lines:

```
var googleProtoFiles = require('google-proto-files');
var googleProtoFilesDir = googleProtoFiles('..');
```

@guybedford Can you fix this?
