### ISSUE TITLE
TypeError: Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by brielov** [zeit/ncc#336]
I'm trying ncc for the first time with a simple express server and when I use --v8-cache this error pops up.

> ncc build -m --v8-cache index.js
TypeError: Cannot read property 'byteLength' of undefined
    at renderSummary (evalmachine.<anonymous>:1:28261)
    at handler (evalmachine.<anonymous>:1:31623)

```javascript
// index.js

import http from 'http';
import express from 'express';
import morgan from 'morgan';
import helmet from 'helmet';
import cors from 'cors';
import bodyParser from 'body-parser';
import { version } from './package';

const app = express();

app.use(morgan('combined'));
app.use(helmet());
app.use(cors());
app.use(bodyParser.json());

app.get('/', (req, res) => res.json({ version }));

const server = http.createServer(app);

server.listen(() =>
  console.log(`server listening on http://127.0.0.1:${server.address().port}`),
);
```

I'm running macOS Mojave on a 13" macbook pro

**Comment by guybedford** [comment]
Thanks so much for reporting, I can confirm this is a bug, and the fix is included in #337.
