### ISSUE TITLE
--watch not working?

### ISSUE THREAD

**Issue by dpeek** [zeit/ncc#342]
The watch flag doesn't seem to work for me.

To reproduce in empty dir:

```
yarn init -y
yarn add @zeit/ncc
echo "console.log('test');" >> index.js
ncc build index.js # works
ncc build index.js --watch # fails without error
```

Environment:

```
$ node --version
v11.13.0
$ ncc version
0.17.2
```

**Comment by dpeek** [comment]
Works for me, thanks for the quick fix!

Side note: is there a way to get yarn link working with binaries (like ncc cli)? Would like to use this fix before you cut a new release.

**Comment by guybedford** [comment]
@dpeek you're welcome. Do you mean the issue is `yarn link` doesn't create a `node_modules/.bin/ncc` entry? That seems like a linking issue to me, although the fix would be to just run `node_modules/ncc/dist/ncc/cli.js` instead.
