### ISSUE TITLE
Issues with multi-database libs: sequelize

### ISSUE THREAD

**Issue by konsumer** [zeit/ncc#345]
I am having trouble using any multi-database wrappers (tried sequelize and any-db) with ncc.

Let's take, for example, a URI like `sqlite:///tmp/demo.sqlite`, which works fine locally in an express service. If I compile with ncc, it runs fine if the output is in the same dir (where sqlite3 is installed.)

[Here](https://spectrum.chat/zeit/now/module-initialization-error-with-sequelize~727fd4ce-43f6-4544-8504-9c0a4889564a) is me troubleshooting with now.sh.

[Here](https://github.com/konsumer/demo-db) is a demo-repo that illustrates the problem. If I deploy or build locally but move the folder out of the project that has sqlite3 installed, it exhibits the problems above.

To reproduce:

```
git clone https://github.com/konsumer/demo-db.git
cd demo-db
npm i

ncc build node/index.js                                                              # builds fine
DATABASE_URI="sqlite:///tmp/demo.sqlite" node dist/index.js # runs fine

mv dist ~/Desktop
cd ~/Desktop/dist
DATABASE_URI="sqlite:///tmp/demo.sqlite" node index.js

/home/konsumer/Desktop/dist/index.js:28596
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/konsumer/Desktop/dist/index.js:28596:15)
    at new ConnectionManager (/home/konsumer/Desktop/dist/index.js:21768:21)
    at new SqliteDialect (/home/konsumer/Desktop/dist/index.js:37324:30)
    at new Sequelize (/home/konsumer/Desktop/dist/index.js:22307:20)
    at Object.<anonymous> (/home/konsumer/Desktop/dist/index.js:72980:19)
    at __webpack_require__ (/home/konsumer/Desktop/dist/index.js:22:30)
    at startup (/home/konsumer/Desktop/dist/index.js:36:19)
    at /home/konsumer/Desktop/dist/index.js:42:18
    at Object.<anonymous> (/home/konsumer/Desktop/dist/index.js:45:10)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11

```

Might be related to #74

**Comment by konsumer** [comment]
Without using a multi-db manager, it seems to work great:

```js
const { Database } = require('sqlite3')

const db = new Database(process.env.DATABASE_URI.replace(/^sqlite:\/\//, ''))

const query = q => new Promise((resolve, reject) => db.all(q, (err, rows) => err ? reject(err) : resolve(rows)))

const run = async () => {
  const r = await query('SELECT 1+1 AS result')
  console.log(r[0].result)
}
run()
```

and creates a atomic dist folder that looks like this:

```
├── index.js
├── lib
│   └── binding
│       └── node-v67-linux-x64
│           └── node_sqlite3.node
├── node-pre-gyp
│   ├── appveyor.yml
│   ├── bin
│   │   ├── node-pre-gyp
│   │   └── node-pre-gyp.cmd
│   ├── CHANGELOG.md
│   ├── contributing.md
│   ├── lib
│   │   └── util
│   │       ├── abi_crosswalk.json
│   │       └── nw-pre-gyp
│   │           ├── index.html
│   │           └── package.json
│   ├── LICENSE
│   ├── package.json
│   └── README.md
├── nw-pre-gyp
│   ├── index.html
│   └── package.json
└── package.json
```

**Comment by konsumer** [comment]
[Here](https://demo-db.dkonsumer.now.sh/node-nomanage/) is [that code](https://github.com/konsumer/demo-db/blob/master/node-nomanage/index.js) running on now.

Also tried knex, which seemed to work fine, so I might end up just using that.

**Comment by styfle** [comment]
Hi @konsumer thanks for the bug report!

There is a lot here so maybe we can isolate it to one specific issue.

> Without using a multi-db manager, it seems to work great:

What is a multi-db manager?

You might also be interested in these related issues to DBs:

https://github.com/zeit/now-builders/issues/331#issuecomment-479034684

https://github.com/zeit/now-builders/issues/335#issuecomment-480009057

**Comment by konsumer** [comment]
> What is a multi-db manager?

I tested with sequelize and any-db. What I mean is a lib that lets you use multiple databases with the same code. I would call it an ORM, but any-db isn't an ORM, just a lib that lets you talk to multiple SQL databases with the same code. For further testing I tried knex, and it seemed to work ok, so for my use-case I might just use that.

> You might also be interested in these related issues to DBs:

Thanks!

Link 1: Since the code works fine compiled in ncc, directly, as long as it's in the same dir that has node_modules, but not if not, I think it's a problem with ncc or how now is bundling node_modules. The linked issue is about setting up other things (AWS credentials for RDS) but my example literally just opens a sqlite file in /tmp and does `SELECT 1+1`. no other settings are needed. The examples also verify that the path tho the sqlite file is correctly inserted into env vars as /tmp/demo.sqlite

Link 2: This is getting closer to my issue, I think, in that the mongodb-person is saying "mark it as an external module" which ncc is definitely doing automatically with sqlite3 (again, compiled code works fine in same project that has sqlite installed in node_modules, but not if you take the compiled dir out of that folder.) Again, this points to now's method of dealing with node_modules or how ncc bundles the deps. Since someone from the now team said to report it here, I am doing that.

**Comment by styfle** [comment]
Have you tried adding `const sqlite = require('sqlite3')` before sequelize?
Or tried using config.bundle = false? 

See my comment here: https://github.com/zeit/now-builders/issues/331#issuecomment-478679523

**Comment by konsumer** [comment]
> Have you tried adding const sqlite = require('sqlite3') before sequelize?

Yeh, this was my first idea, to prime the dependency-tree. I get `module initialization error: Error` with no clear reason why.

* [Here](https://demo-db-hnzd7ltc7.now.sh/node) is that running on now.
* [Here](https://github.com/konsumer/demo-db/blob/77aea9139a743c14ba0747430ff60adb72fda554/node/index.js) is the code.

> Or tried using config.bundle = false?

I combined both suggestions, and got the same error.

* [Here](https://demo-db-lpnuimenc.now.sh/node) is both suggestions running on now.
* [Here](https://github.com/konsumer/demo-db/tree/9066e8a59c5f56a2076ad93a4422d9a0a580ffc1) is the code.

**Comment by styfle** [comment]
`config.bundle` only works with the `@now/node-server` builder.

Also, you might try creating separate `now.json` files in each directory instead of one at the top level of the monorepo. Maybe the bug only shows up with monorepos 🤔

**Comment by konsumer** [comment]
> config.bundle only works with the @now/node-server builder.

That works. Awesome!

* [Here](https://demo-db-n7kivxyxx.now.sh/node-server/) is that running on now.
* [Here](https://github.com/konsumer/demo-db/tree/1071516f78a4950673a676fdabeefa7cc10d6c88) is the code.

If you want to test out more ideas, feel free to use my [demo repo](https://github.com/konsumer/demo-db) as it has a few permutations that illustrate the problem.

> Also, you might try creating separate now.json files in each directory instead of one at the top level of the monorepo. Maybe the bug only shows up with monorepos

A big part of my reason for wanting to use now in my situation, is that it simplifies a single host with multiple lambda mount-points. If I can't have that sort of setup, I see little advantage over serverless. I mean, I can even do that with serverless, it just takes a little more configuration. up also does separate individual endpoints simply, and doesn't have this problem.

This node-server solution seems like an OK middleground, even though I'm not getting the improve sizes bundling offers, or the other advantages of @now/node, but I can mix the one service that needs a database in with others that don't need it, so I can totally live with that. Thanks!

**Comment by guybedford** [comment]
Just had a quick look at this one, and it seems the untraceable dynamic require is in https://github.com/sequelize/sequelize/blob/7445423b9effc212e125d76d58e02713e808ffc6/lib/dialects/abstract/connection-manager.js#L69.

Configuring `--external sqlite` should also get this to work here with `ncc`, although I'm not sure how that same workflow would look in Now.

**Comment by konsumer** [comment]
@guybedford thanks for taking a look. That's a great tip for working around dynamic modules in ncc. I ended up just using knex on now, which seems to work great with `@zeit/node@canary` builder.

**Comment by styfle** [comment]
@guybedford Can we implement a workaround to get `sequelize` working?

There are other reports of a similar issue when using `sequalize` and `pg` here: https://github.com/zeit/now-builders/issues/331

**Comment by guybedford** [comment]
The workaround here is to pass the dialect to the Sequelize initialization itself.

So instead of having:

```js
let db = new Sequelize({
  dialect: 'pg'
});
```

You would do:

```js
let db = new Sequelize({
  dialect: 'pg',
  dialectModule: require('pg')
});
```

where that then avoids the internal dynamic require which would just do `require(config.dialect)`, which is the thing we can't analyze.

**Comment by zdne** [comment]
I can confirm this is still issue with the current version and sequelize v5. Adding `dialectModule: require('pg')` as @guybedford suggested helps.

**Comment by thisjeremiah** [comment]
Similarly, I can confirm that adding dialectModule: require('sqlite3') worked for me.

**Comment by aecorredor** [comment]
I'm having the same issue, but my dialect has always been `postgres`, not `pg`. I'm guessing they are the same. Even with `require('pg')`, I still get the following error instead: `Cannot find module 'pg-native'`

**Comment by konsumer** [comment]
@aecorredor you should be able to do it with this:

```js
const db = new Sequelize({
  dialect: 'postgres',
  dialectModule: require('pg-native')
});
```

**Comment by traderjosh** [comment]
`dialectModule: require('pg-native')`
Didn't fix it for me

And `dialectModule: require('pg')` is giving me many errors such as `ModuleNotFoundError: Module not found: Error: Can't resolve 'dns'`

**Comment by jmsunseri** [comment]
> should

what does this mean?  i tried adding 

```
vite: {
			build: {
				rollupOptions: {
					external: ['pg-native']
				}
			}
		}
```
or
```
vite: {
			build: {
				rollupOptions: {
					external: ['pg']
				}
			}
		}
```
neither seems to fix the issue
