### ISSUE TITLE
Go-style signature

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#35]
The more I think about it, the more I'd like to support:

```
$ ncc run
```
and
```
$ ncc build
```

We would:
- [x] Add support for `pkg.main` / `index.js` if no argument is supplied
- [ ] `run` to build to a temporary location and clean it up on a best-effort basis
- [x] `build` to output to a default `dist` directory if `-o` is not supplied (in tandem with #30)

**Comment by rauchg** [comment]
To elaborate on this:

>  clean it up on a best-effort basis

This would imply doing it on `beforeExit` or a similar process / signal hook.

**Comment by rauchg** [comment]
Done

**Comment by guybedford** [comment]
These are all completed.
