### ISSUE TITLE
Incorrect source maps for typescript

### ISSUE THREAD

**Issue by styfle** [zeit/ncc#353]
## Steps to reproduce

```
git clone https://github.com/styfle/ncc-bug-stack
cd ncc-bug-stack
git checkout ts
yarn
yarn build
node dist
```

Then visit http://localhost:3000

Notice the stack trace shows `ncc-bug-stack/index.ts:6:1`

## Expected

The expected line number is [index.ts:4](https://github.com/styfle/ncc-bug-stack/blob/ts/index.ts#L4), not `6`.

Also the column number is wrong (but that is less important).

**Comment by guybedford** [comment]
I just ran the example build in the source map visualization tool (https://sokra.github.io/source-map-visualization/#custom) and the source map is definitely 100% correct (see below)
![Screenshot from 2019-04-18 19-11-40](https://user-images.githubusercontent.com/598730/56378748-3b920400-620e-11e9-899e-2dc69f63a992.png)

So this means the issue must lie with https://github.com/evanw/node-source-map-support or v8 itself here unfortunately.

**Comment by guybedford** [comment]
I also tried this against the unbuilt non-ncc version of source-map-support and the same applies, so it's definitely the source map support package itself.

**Comment by guybedford** [comment]
Ahh wait, in the example above the `index.ts` is not the original ts file but actually the ts converted to js....

So it should be as simple as fixing up the sourcemap chaining support here.
