### ISSUE TITLE
confusing about how to use it Programmatically

### ISSUE THREAD

**Issue by lili21** [zeit/ncc#354]
I guess I need a more clear [explanation](https://github.com/zeit/ncc#programmatically-from-nodejs).

I'd like do it programmatically and I want it output file and directory just like `ncc build`. what should I do ?

**Comment by guybedford** [comment]
The CLI itself is just a thin wrapper around ncc. See how it is used for example in https://github.com/zeit/ncc/blob/master/src/cli.js#L213.

**Comment by styfle** [comment]
This might help: https://github.com/styfle/ncc-bug-stack/blob/master/build.js#L7

**Comment by lili21** [comment]
Thanks.
