### ISSUE TITLE
Running ncc generates async-hook-jl

### ISSUE THREAD

**Issue by kennetpostigo** [zeit/ncc#356]
I noticed that on some services running `ncc` generates a `mime.types` file and `async-hook-jl` folder with a `LICENSE.md`, `README.md`, `yarn.lock`, and `package.json`. I'm not sure why exactly that is. But when this happens my services stop working and I get timeouts on my requests in production. Running the generated output from  `ncc` works, I checked locally with postman to test out the lambda. Theres no heavy computations or anything going on, just an API call to `mailgun` or `twillio`.

![image](https://user-images.githubusercontent.com/8888991/56462084-cb5cbd00-638a-11e9-9fd6-8820a47238f3.png)

I also noticed the following in `now` where my `Source` directory structure differs from the `Output` directory structure of the `dist` folder. 

Heres the `Source`:
![image](https://user-images.githubusercontent.com/8888991/56462147-2ba02e80-638c-11e9-9efc-f4cb91f7aac8.png)

Heres the `Output`:
![image](https://user-images.githubusercontent.com/8888991/56462143-1c20e580-638c-11e9-9929-b8857bbe914f.png)

I'm not sure whether the `dist/index.js` depends on anything inside of the `async-hook-jl` or `mime.types` file, and if it's not in the `Output` directory that may cause it to look for those and timeout b/c it can't find them.

**Comment by guybedford** [comment]
@kennetpostigo did you close this because you managed to make progress on the issue? If there is something we can look into here further please do post an update.

**Comment by kennetpostigo** [comment]
@guybedford I was able to get around this by making a route for these files. But i'm still a bit curious as to why these files get generated.

**Comment by guybedford** [comment]
@kennetpostigo I'm working on a PR to add a `--debug` flag to the CLI that will log the reasons for all the assets being emitted. Should help us to better catch and identify unnecessary cases, although the asset emission is slightly overclassifying by default to value running code over neatness :)
