### ISSUE TITLE
run code even when there is typescript errors

### ISSUE THREAD

**Issue by sibelius** [zeit/ncc#357]
If my code has some type errors it won't let me run my code

can we skip typecheck errors when trying to run typescript code?

I'm trying to run this repo https://github.com/entria/entria-fullstack

```
ncc run packages/server/src/index.js
```

**Comment by styfle** [comment]
TypeScript has a flag for this: `noEmitOnError` in the [tsconfig.json](https://www.typescriptlang.org/docs/handbook/compiler-options.html) file.

But your example is not compiling a `.ts` file? Why is that?

**Comment by sibelius** [comment]
we have mixed js and ts files in that project

we are in the middle of a migration

**Comment by sibelius** [comment]
tried with `noEmitOnError: true` and `noEmitOnError: false` in all tsconfig of the workspaces

it gave the same output

even `ncc build` throws the same errors

**Comment by guybedford** [comment]
This is a limitation of the ts-loader. This is very similar to #321 in that the TypeScript validations are exhaustive (exhaustingly :P).

**Comment by guybedford** [comment]
I've created a main tracking issue for this feature in https://github.com/zeit/ncc/issues/362. Marking this as a duplicate.
