### ISSUE TITLE
TypeScript dist includes entire project

### ISSUE THREAD

**Issue by Jefftopia** [zeit/ncc#359]
## Problem
When building a project using typescript and bundling node_modules, the project contents are all curiously included in the dist directory. 

## Steps to reproduce
1. I cloned this project.
2. In the `examples` directory, `cd` into `typescript`. 
3. `npm install --save jovo-framework`. 
4. Make your `index.ts` look like this:

```
import chalk from "chalk";
import { Lambda } from 'jovo-framework';

function logSuccess(msg: string) {
  console.log(chalk.green(msg));
}

logSuccess("Hello World!");

export const handler = async (event, context, callback) => {
  console.log(`[AWS Lambda Handler]`);
  console.log(event, '\n\n', context);
  return new Lambda(event, context, callback);
};
```

>NB: Above code doesn't actually do anything noteworthy!

5. Use the default `tsconfig.json` settings:

```
{
    "compilerOptions": {
      "target": "es2015",
      "moduleResolution": "node"
    }
}
```

6. Now drill into the default build dir, `dist/`
7. Notice that there's a directory called `typescript`, which contains all of the cwd.

## Environment
- `ncc`: ^0.18.1
- node: v9.5.0
- npm: 6.9.0
- TypeScript: 3.4

**Comment by styfle** [comment]
@guybedford We need to release `webpack-asset-relocator-loader` and submit a PR to `ncc` before this issue can be closed. I'll open it for now.

**Comment by Jefftopia** [comment]
Thanks @guybedford
