### ISSUE TITLE
Transpiling fails in prod, but apparently not in dev

### ISSUE THREAD

**Issue by deitch** [zeit/ncc#360]
Reference [this issue in spectrum](https://spectrum.chat/zeit/now/transpiling-for-es6-modules-and-node-server~b4d781e9-8f55-4374-aac7-bb91f11e4fcb) with @paulogdm .

If I use transpiling, there appears to be no way to get the transpiling to work. According to @paulogdm it does work in `now dev` but not in the actual released product. He created an example that works [here](https://avitest.pgdm.now.sh/_src), but only with `@now/node-server@canary`.

I assume that since this is in canary, it is fixed and will be released soon, bit I couldn't find an existing closed issue, which means it probably should be tracked, and then this can be closed.

**Comment by styfle** [comment]
Hi @deitch 

If it worked in `@now/node-server@canary` then it should work in `@now/node-server` today since we released stable.

You don't need to file bugs for things that are fixed in canary because they will get released to the stable channel periodically.

Thanks!

**Comment by deitch** [comment]
Hi @styfle 

I figured as much, but since there was no issue reporting it (or at least one that I could find), I figured you would be happier with an issue that is closed immediately for future tracking. 

I will test on latest stable and close out if it is gone.

**Comment by deitch** [comment]
Confirmed that it works. Thanks!
