### ISSUE TITLE
Deployment fails when using esm module

### ISSUE THREAD

**Issue by deitch** [zeit/ncc#361]
One of the "transpile-less" ways to get es6 modules working is the [esm module](https://www.npmjs.com/package/esm). This appears to break with `now`, both current release and `@canary`. Verified with @paulogdm in [this discussion](https://spectrum.chat/zeit/now/transpiling-for-es6-modules-and-node-server~b4d781e9-8f55-4374-aac7-bb91f11e4fcb).

Sample code is available [here](https://github.com/deitch/now-avitest) which is available deployed at https://avitest.deitch.now.sh

**Comment by guybedford** [comment]
We could add a special exception for esm support.

**Comment by deitch** [comment]
Ah, you know why it fails? I wasn't sure if it was a known issue or not. Would be happy if you would elaborate?

**Comment by deitch** [comment]
Awesome thank you. Is this deployed, or do I need to run `@canary`?

**Comment by styfle** [comment]
@deitch It hasn't been updated in the builder yet. Here is the PR: https://github.com/zeit/now-builders/pull/446

**Comment by deitch** [comment]
Thanks, I will follow that one.

**Comment by deitch** [comment]
Thanks, I will follow that one.
