### ISSUE TITLE
Express templates app.engine support

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#364]
We fixed the express case of `app.engine('name', 'value')`, but there is a pattern of using the consolidate npm package (https://www.npmjs.com/package/consolidate):

```js
app.engine('name', consolidate.name)
```

where the consolidate implementation will then do a dynamic require to the underlying template engine by name.

I'm not sure how best to support this - we could special case this consolidate workflow.

**Comment by styfle** [comment]
@guybedford At 1 million weekly downloads this sounds like a popular solution. If we need to special case it, let's do it 👍

**Comment by guybedford** [comment]
Ok so it turns out this is actually a different way of using Express engines than what we handled previously.

The scenario is that:

```js
app.set('view engine', 'name')
```

corresponds to `app.set('view engine', require('name').__express)`, BUT the other pattern used in Express is:

```js
app.engine('name', customImplementation);
app.set('view-engine', 'name');
```

where this case will use the `app.engine` value instead of doing `require('name').__express`!

So we need to support this pattern as an alternative by checking if `app.engine` has been called.
