### ISSUE TITLE
Possible v8 cache bug

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#395]
The next.js testing revealed a possible v8 cache bug with a CI failure on Azure on Node.js 10 with that was resolved by opting out of the v8 cache.

Without being able to directly diagnose this v8 bug, it may be worthwhile to disable the cache entirely, as the minor perf benefit doesn't seem worth exposing a possible v8 bug to users.

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/57977125-f6870a80-7a23-11e9-8ecb-ee6458a7a129.png)

**Comment by guybedford** [comment]
Resolved in #404.
