### ISSUE TITLE
Could this be used to package a webserver?

### ISSUE THREAD

**Issue by zeke** [zeit/ncc#415]
I have an Express-powered website that I'd like to be able to distribute as a downloadable package, so people with limited connectivity can run it locally. Is ncc an appropriate tool for this?

Picturing this:

```sh
$ run-that-website

// that website is now running on localhost:3000
```

**Comment by styfle** [comment]
I think you might be interested in [pkg](https://github.com/zeit/pkg) which includes the Node binary. The difference is that `ncc` only bundles the js files together like webpack or rollup so you would still need to ship a Node executable.

**Comment by rauchg** [comment]
You might also be interested in a combination of `ncc` and `pkg`
