### ISSUE TITLE
Is JSX supported?

### ISSUE THREAD

**Issue by karl-run** [zeit/ncc#428]
I'm trying to use ncc for a simple [Ink](https://github.com/vadimdemedes/ink) project.

`index.jsx`:

```jsx
import React, { Component } from "react"
import { render } from "ink"

class Counter extends Component {
  render() {
    return <div>Example</div>
  }
}

render(<Counter />)
```

Running `ncc build index.jsx -o dist/index.js` yields:

```plain
$ ncc build index.jsx -o dist/index.js
ncc: Version 0.19.1
ncc: Compiling file /home/karl/git/ttgo/index.jsx
Error: Module parse failed: Unexpected token (6:11)
You may need an appropriate loader to handle this file type.
| class Counter extends Component {
|   render() {
>     return <div>Example</div>
|   }
| }
    at evalmachine.<anonymous>:3:801057
    at eval (eval at create (evalmachine.<anonymous>:3:2198939), <anonymous>:13:1)
```

It works fine if I use TypeScript. I can't find anywhere in the documentation on whether or not it should work with plain JSX.

**Comment by rauchg** [comment]
It's not supported. We support Node.js or TypeScript. Trying to remain zero-config and zero-plugin fro the moment

**Comment by karl-run** [comment]
Alright thats fine. Might be useful to state that in the README? Might just be me but I didn't realize that it was the TypeScript compiler that parsed the JSX in the TSX files, so when I read that TSX was supported I made the bold assumption that JSX would be as well. 🤷‍♂️
