### ISSUE TITLE
Add `--filename` option

### ISSUE THREAD

**Issue by MaximDevoir** [zeit/ncc#492]
It would be great if `ncc build` supported an option such as `--filename` to allow naming the generated file to something other than `index.js`.

It looks like the application was built to support this option in the future with the following lines already in place:

https://github.com/zeit/ncc/blob/0ad6971d202ee5896310f65e9aedfd1156184346/src/index.js#L39

https://github.com/zeit/ncc/blob/0ad6971d202ee5896310f65e9aedfd1156184346/src/index.js#L53

https://github.com/zeit/ncc/blob/0ad6971d202ee5896310f65e9aedfd1156184346/src/index.js#L131-L134

**Comment by tunnckoCore** [comment]
I "wanted" such feature in the beginning. The answer to that is you can name the out folder however you want. And I can agree with that, plus consistency - output will always end in index.js

**Comment by joeldenning** [comment]
I talked to @guybedford about this today - he said the js api supports this and he'd be open to a PR adding support for changing the output filename via CLI

**Comment by tcurdt** [comment]
I am a little confused - why did you close the issue, @MaximDevoir ?
