### ISSUE TITLE
Add examples folder

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#50]
- [ ] Hello world
- [ ] Multiple bundles (e.g.: `cli.js` -> `dist/cli/` and `main.js` -> `dist/main`)

**Comment by macklinu** [comment]
Would also be good to add examples for programmatic use and TypeScript support 😎 

Can get started on a PR for these

**Comment by maxbeatty** [comment]
What's the optimal way to do multiple bundles? Programmatic?

Would there ever be a day where `ncc` takes a glob to build? (e.g. `ncc build *.js` or `ncc build {cli,main}.js`)

**Comment by macklinu** [comment]
@maxbeatty looks like there is a little bit of talk about supporting multiple entry points in #113. As of now, I believe the only way to support multiple bundles right now would either be:

```sh
ncc build a.js -o dist
ncc build b.js -o dist
```

or with a custom build script using the ncc Node API:

```js
const path = require('path')
const ncc = require('@zeit/ncc')

// Whatever options you want. This is an example.
const options = {
  minify: true,
  sourceMap: true,
  watch: false,
}

Promise.all([
  ncc(path.resolve('./a.js'), options),
  ncc(path.resolve('./b.js'), options),
])
  .then(([a, b]) => {
    // Builds succeeded!
    // You can write the code and sourcemaps to disk or whatever you'd like to do here.
    console.log(a.code)
    console.log(a.assets)
    console.log(a.map)
  })
  .catch((err) => {
    // There was an error in one of the builds.
    console.error(err)
  })
```

(where `a.js` and `b.js` live in the folder you are running the script from. Those sorts of file paths would need to be updated to suit your needs.)

I think examples for programmatic use (both for one entry point and multiple entry points) would be welcome additions to this repo to help guide people in understanding what options are available / best practices are around multiple bundles + programmatic use. 👍

**Comment by guybedford** [comment]
Examples were added in https://github.com/zeit/ncc/commit/c813b07096f2d3e89dae9a3d0917413a2c19ba24.

We can reopen if we need to add any new examples.
