### ISSUE TITLE
V8 Compile Cache

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#51]
The idea is that we can emit not just `.js` files, but also the v8 code cache blobs.
And unlike `v8-compile-cache`, we could benefit from making all bootups fast, including the first one. Also unlike it, we can use the new `createCachedData` APIs which have some benefits.

- [ ] Make sure we disable the optimization gracefully when invoking in old Node versions
- [ ] Make sure to add a flag to disable it (`--no-v8-cache`)

More:
- https://github.com/nodejs/node/pull/20300
- https://github.com/nodejs/node/commit/4f67c6f667fa98e25ba311d3459fc8e270407250
- https://github.com/Microsoft/vscode/issues/62643
- https://nodejs.org/dist/latest-v10.x/docs/api/vm.html#vm_script_createcacheddata
- (legacy) https://nodejs.org/api/vm.html#vm_new_vm_script_code_options `produceCachedData`
- (legacy) https://www.npmjs.com/package/v8-compile-cache

**Comment by rauchg** [comment]
It'd be neat to self-host this as well. Right now `ncc` takes 350ms~ to boot up, and the TypeScript compiler adds another 350ms~.

**Comment by guybedford** [comment]
I just ran a simple test of the following code:

create-cache.js
```js
const fs = require('fs');
const { Script } = require('vm');
const script = new Script(fs.readFileSync('./index.js').toString());
fs.writeFileSync('./index-cache', script.createCachedData());
```

index-cached.js
```js
const fs = require('fs');
const source = fs.readFileSync('./index.js').toString();
const cachedData = fs.readFileSync('./index-cache');
console.log(new Script(source, { cachedData }).cachedDataRejected);
```

where we then compare running `node index-cached.js` and `node index.js`.

Here are the results:

* 

I just ran a test of the above

**Comment by simlu** [comment]
We're getting a `TypeError: (intermediate value).createCachedData is not a function`.

Is anyone still using this or has an idea what is going on?

**Comment by simlu** [comment]
I'm guessing this doesn't work when executing programmatically?

**Comment by guybedford** [comment]
@simlu are you explicitly using the `--v8-cache` flag here with an `ncc build` workflow? Yes it would not be supported in Node 8 though, as this is a recent v8 feature.

**Comment by sourcevault** [comment]
how big has the build has to be useful ? 0.5 MB, 2 MB ? 100 MB ?
