### ISSUE TITLE
NPM release 0.22.0 was built with 0.21.1

### ISSUE THREAD

**Issue by jclem** [zeit/ncc#524]
When installing `@zeit/ncc` from NPM, the compiled version is still 0.21.1:

![image](https://user-images.githubusercontent.com/412282/77465205-a9f82280-6dde-11ea-8118-be994262fd8a.png)

When building from source and calling `dist/ncc/cli.js`, the version is 0.22.0, so I'm guessing the latest release just wasn't built accidentally.

**Comment by Djiit** [comment]
Ahah I was becoming crazy.

**Comment by styfle** [comment]
Thanks! This is probably from the problems we had with building/testing on Node 12.

I published a new version: `0.22.1`.
