### ISSUE TITLE
[Question] why npm/yarn/pnpm contributed to the bundle size?

### ISSUE THREAD

**Issue by 3cp** [zeit/ncc#541]
For my project https://github.com/makes/makes
The ncc yields noticeable difference between deps installed by npm, yarn, and pnpm. All the three produce functional output.
I am confused why it's sensitive to different package managers, any explanation?

Clean install with NPM 358kB
```
⋊> ~/m/makes on master ◦ npm i

> makes@1.5.0 prepare /Users/huocp/makesjs/makes
> npm run build


> makes@1.5.0 build /Users/huocp/makesjs/makes
> ncc build lib/index.js -m

ncc: Version 0.22.1
ncc: Compiling file index.js
358kB  dist/index.js
358kB  [4014ms] - ncc 0.22.1
```

Clean install with Yarn 370kB
```
⋊> ~/m/makes on master ◦ yarn
yarn install v1.22.4
...
> makes@1.5.0 build /Users/huocp/makesjs/makes
> ncc build lib/index.js -m

ncc: Version 0.22.1
ncc: Compiling file index.js
370kB  dist/index.js
370kB  [4518ms] - ncc 0.22.1
✨  Done in 15.95s.
```

Clean install with Pnpm (with shamefully-hoist=true in my npmrc) 324kB
```
⋊> ~/m/makes on master ◦ pnpm i
...
> makes@1.5.0 build /Users/huocp/makesjs/makes
> ncc build lib/index.js -m

ncc: Version 0.22.1
ncc: Compiling file index.js
324kB  dist/index.js
324kB  [4429ms] - ncc 0.22.1
```

**Comment by AviVahl** [comment]
Possible causes:
- npm adds extra metadata to `package.json` files in node_modules. If a package imports/requires it's own package.json (some packages do, to refer to `name/version` fields), then these files would have a different size than yarn (v1) and pnpm.
- pnpm chosen `node_modules` structure dedupes "same version" better. You always get a single copy of each version. That's not the case for npm/yarn (v1), where naive bundling may bundle the same version twice (or more), if ends up sitting in several places across `node_modules`.

**Comment by 3cp** [comment]
Thx! That sounds right. I knew npm added meta into package.json, but couldn't understand why yarn is the biggest. Good to know pnpm does extra to remove duplicates.

**Comment by AviVahl** [comment]
Oh, didn't even notice npm ended up producing smaller bundles. There are other subtle differences to npm and yarn's resolution algorithms. For example, npm dedupes `"*"` better, picking the latest version *already in the tree*, while yarn treats it as `"latest"`, and usually ends up creating additional duplicates.
