### ISSUE TITLE
project deployment with nestjs using @ nestjs / platform-socket.io

### ISSUE THREAD

**Issue by henriqueweiand** [zeit/ncc#543]
I'm having problems deploying my project after adding the use of websockets.

I've been researching and I've found other related issues, but none with a solution. Does anyone know how to give me a way forward to solve this problem?

![Screen Shot 2020-05-21 at 00 12 52](https://user-images.githubusercontent.com/6539492/82519352-d509a480-9af7-11ea-8b9e-6c45dcb9381d.png)

project: https://github.com/toworld-dev/scrum-poker-online

related #513

**Comment by paulogdm** [comment]
The Vercel platform does not support WebSockets. Also, this repository is unrelated to the platform because the latest versions of our runtimes don't use NCC.
