### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#62]
Currently, `minimize: true` being turned on is failing for an unknown reason with all integration tests.

We should be mindful here to only enable optimizations that are deemed safe for most Node.js programs and npm modules (including those that perform runtime introspection or reflection).

The pros / cons of this have to be carefully evaluated in contrast with what #51 provides.

**Comment by developit** [comment]
Would it be useful to start off with simple whitespace + comment removal?
