### ISSUE TITLE
Filenames of resources must be unique to avoid a crash

### ISSUE THREAD

**Issue by baboons** [zeit/ncc#65]
Considering the examples for NCC with Apollo and an abstract structure with schemas as resources and sharing the same filenames. This will cause NCC to compile the first/last file only, and throwing an error. 

```
schemas\
      blogs\
           index.js
           schema.gql
      posts\
           index.js
           schema.gql
```

Output

```
   3kB  /schema.gql
6127kB  /index.js
```

At the moment this can only be resolved by renaming one of the schemas and make sure the file names are unique:

`const typeDefs = String(fs.readFileSync(__dirname + "/schema2.gql"));`

Output

```
   1kB  /schema2.gql
   3kB  /schema.gql
6127kB  /index.js
```

**Comment by rauchg** [comment]
I'll close until we hear from @baboons whether this is happening on 0.3.0+
