### ISSUE TITLE
Bundle Node builtins

### ISSUE THREAD

**Issue by tunnckoCore** [zeit/ncc#71]
Currently, it seems it does not bundle them, because I can find

```js
/* 0 */
/***/ (function(module, exports) {

module.exports = require("process");

/***/ }),
```

In the bundle. And worse, it does not use the webpack require but the normal one and I can bet it won't work in the browser.

Even without this problem, it still won't work in the browser because it `module.exports = webpack stuff`, so I can suggest a new flag to bundle for the browser.

**Comment by styfle** [comment]
I don't think the goal of `ncc` is to run in the browser (that would basically be `browserify`).

The motivation in README says "Only ship relevant app code to serverless environments"

It's meant for the server (ironically, serverless here is a type of server).

**Comment by rauchg** [comment]
Browser shims are a non-goal for `ncc`. It's meant to bundle Node.js apps.
