### ISSUE TITLE
ncc -M (unexpected option)

### ISSUE THREAD

**Issue by navossoc** [zeit/ncc#72]
I think there is a typo here.

https://github.com/zeit/ncc/blob/554c2ae32baa70159e856c75e8639775c9550988/src/cli.js#L26

It shouldn't be `"-M": "--no-minify"`?

`ncc build -M` fails with:
`Unknown or unexpected option: -M`

Also, I didn't see any difference running:
`ncc build` or
`ncc build --no-minify`

Is minification disabled for now because of the issue #62?

[]'s

**Comment by tunnckoCore** [comment]
I was thinking to post the exact same issue before a few days. I think it is disabled at all now because of #62.

**Comment by guybedford** [comment]
Yes, minification fixes are tracking in #62.
