### ISSUE TITLE
Ignore option

### ISSUE THREAD

**Issue by dy** [zeit/ncc#73]
Sometimes an output bundle is designed to be a dependency, not final destination, and that would be useful to keep some its deps not packed, to share them with adjacent modules. Or the case of optional dependencies, included only if they are required by the adjacent modules.

With rollup-plugin-commonjs there is ‘ignore’ option for that.

Is there any plan to include that for ncc?

**Comment by rauchg** [comment]
Is the current `-e` not good enough for this?

**Comment by dy** [comment]
Bah, should've read more carefully. Thanks.
