### ISSUE TITLE
An amd test proposal

### ISSUE THREAD

**Issue by igorklopov** [zeit/ncc#82]
Let's add this snippet as a test for https://github.com/zeit/ncc/commit/f1eec46f7958564fe9f095894947e2aa09ed8057
```
console.log(
  ('function' === typeof define) && (define.amd != null)
);
```
Compiled javascript must return `false`. Without the commit, compiled snippet crashes.

**Comment by guybedford** [comment]
@roychri I had a look at your case, and found https://github.com/zeit/ncc/pull/92 which seems to be at least one bug affecting jugglingdb builds here. I was able to get jugglingdb to build successfully rewriting `module.js`, `scope.js` and `schema.js` in `lib` to not use `require('when')` and rather just use native promises.

**Comment by roychri** [comment]
@guybedford Thanks very much for taking the time to look at my case. Does this means that anything using `when` will fail to run under `now` as lambda? I do not know much about your build system.
Also, Does this mean that I will be able to deploy with jugglingdb once #92 is fixed?
Thanks again

**Comment by guybedford** [comment]
Note the AMD unit test still hasn't been added here.

**Comment by rauchg** [comment]
@guybedford can you add it ?

**Comment by guybedford** [comment]
Sure, will do.
